# Generated by Django 4.2.2 on 2023-09-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customuser_has_completed_step1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adress_city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='adress_street',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='adress_zipcode',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
