# Generated by Django 4.2.2 on 2023-09-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_requests', '0002_risk_category_risk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='desscription',
            new_name='description',
        ),
    ]
