# Generated by Django 4.2.2 on 2023-09-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_requests', '0003_rename_desscription_risk_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='name',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
