# Generated by Django 4.2.1 on 2023-09-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_requests', '0004_risk_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
