# Generated by Django 4.2.1 on 2023-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_requests', '0005_risk_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
