# Generated by Django 4.2.2 on 2023-09-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_requests', '0006_alter_risk_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('icon_color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='risk',
            name='url',
        ),
        migrations.AlterField(
            model_name='category',
            name='risk',
            field=models.ManyToManyField(blank=True, related_name='related_categories', to='company_requests.risk'),
        ),
        migrations.AddField(
            model_name='risk',
            name='categories',
            field=models.ManyToManyField(related_name='risk_categories', to='company_requests.categoryrisk'),
        ),
    ]
