# Generated by Django 4.2.2 on 2023-09-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_requests', '0009_authorizationscope_userauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationscope',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_scopes', to='company_requests.category'),
        ),
    ]
