# Generated by Django 4.2.2 on 2023-09-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_requests', '0010_authorizationscope_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationscope',
            name='request_type',
            field=models.CharField(choices=[('data_suppression', 'Data Suppression'), ('data_retrieval', 'Data Retrieval'), ('data_modification', 'Data Modification')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
