# Generated by Django 4.2.2 on 2023-09-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_requests', '0011_authorizationscope_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationscope',
            name='request_type',
            field=models.CharField(choices=[('data_suppression', 'Data Suppression'), ('data_retrieval', 'Data Retrieval'), ('data_modification', 'Data Modification')], max_length=30, verbose_name='Type of Request'),
        ),
        migrations.AlterField(
            model_name='companyrequest',
            name='request_type',
            field=models.CharField(choices=[('data_suppression', 'Data Suppression'), ('data_retrieval', 'Data Retrieval'), ('data_modification', 'Data Modification')], default='data_suppression', max_length=30, verbose_name='Type of Request'),
        ),
    ]
