# Generated by Django 4.2.2 on 2023-11-28 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company_requests", "0012_alter_authorizationscope_request_type_and_more"),
    ]

    operations = []
