# Generated by Django 4.2.2 on 2023-11-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_requests", "0013_load_initial_data_company_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
