# Generated by Django 4.2.2 on 2023-12-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_requests', '0014_dataupload'),
    ]

    operations = [
    ]
